[ -h ~/.config ] && rm ~/.config
[ -h ~/.gitconfig ] && rm ~/.gitconfig
[ -h ~/.vimrc ] && rm ~/.vimrc
[ -h ~/.zlogin ] && rm ~/.zlogin
[ -h ~/.zlogout ] && rm ~/.zlogout
[ -h ~/.zpreztorc ] && rm ~/.zpreztorc
[ -h ~/.zprofile ] && rm ~/.zprofile
[ -h ~/.zshenv ] && rm ~/.zshenv
[ -h ~/.zshrc ] && rm ~/.zshrc
